swagger: "2.0"
info:
  description: "This is documentation to accompany the ZippedScript education and enrolment verification API.  You can find out more about ZippedScript and our services by visiting [https://zippedscript.com](https://zippedscript.com)."
  version: "V1.2"
  title: "ZippedScript API"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "info@zippedscript.com"
#host: "127.0.0.1:5000"
host: "zippedscriptapi.com"
basePath: "/v1.2"
tags:
- name: "Account"
  description: "Endoints related to account management"
- name: "Degree Verification"
  description: "Endoints related to verification of degrees"
- name: "Enrolment Verification"
  description: "Endoints related to verification of enrolment"
- name: "Images"
  description: "Endoints related to images - specifically school logos"
schemes:
- "https"
- "http"
paths:
  /account/get_access_token:
    post:
      tags:
      - "Account"
      summary: "Return a valid JWT"
      description: "Endpoint returns a valid JWT bearer token for a respective partner"
      operationId: "getaccesstoken"
      consumes:
      - "application/json"
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "query"
        description: "The user name for login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
      responses:
        '200':
          description: "Success"
          schema:
            type: object
            properties:
              access_token:
                type: string
        "201":
          description: "Request must be of type 'multipart/form-data' or 'application/json' -- or -- Missing parameters"
        "401":
          description: "Bad username or password"
        "503":
          description: "Could not connect to database"
  /account/reset_password:
    post:
      tags:
      - "Account"
      summary: "Reset a password"
      description: "Endpoint allows partners to reset their account password"
      operationId: "resetaccountpassword"
      consumes:
      - "application/json"
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "username"
        in: "query"
        description: "The user name for login"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The password for login in clear text"
        required: true
        type: "string"
      responses:
        '200':
          description: "Password successfully reset"
        "201":
          description: "Request must be of type 'multipart/form-data' or 'application/json' -- or -- Missing parameters"
        "401":
          description: "Bad username or password"
        "503":
          description: "Could not connect to database"
  /account/is_token_valid:
    post:
      tags:
      - "Account"
      summary: "Validate bearer token"
      description: "Endpoint allows partners to validate the proper function of their bearer token"
      operationId: "istokenvalid"
      produces:
      - "application/json"
      responses:
        '200':
          description: "Token verification success"
        "401":
          description: "Missing Authorization Header -- or -- Token has expired"
      security:
      - Bearer: []
  /degree_verification/countries:
    get:
      tags:
      - "Degree Verification"
      summary: "Return a list of available countries"
      description: "Endpoint returns a list of currently available countries for enrolment verification"
      operationId: "degreeverificationgetcountries"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Countries"
  /degree_verification/country/{country_code}:
    get:
      tags:
      - "Degree Verification"
      summary: "Return a list of available schools"
      description: "Endpoint returns a list of available schools for enrolment verification according to the country_code provided"
      operationId: "degreeverificationgetschools"
      produces:
      - "application/json"
      parameters:
      - name: "country_code"
        in: "path"
        description: "2 Letter Country Code in ISO 3166-1 Format"
        required: true
        type: "string"
      responses:
        "200":
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Schools"
        "201":
          description: "Country not found"
  /degree_verification/new:
    post:
      tags:
      - "Degree Verification"
      summary: "Request a new degree verification"
      description: "Endpoint allows partners to request a new degree verification"
      operationId: "degreeverificationnew"
      consumes:
      - "application/json"
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "country"
        in: "query"
        description: "2 letter country code (ISO 3166-1 format)"
        required: true
        type: "string"
      - name: "school"
        in: "query"
        description: "ZippedScript school code/identifier"
        required: true
        type: "string"
      - name: "username"
        in: "query"
        description: "The student username as defined by the school"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The student password for login in clear text"
        required: true
        type: "string"
      responses:
        '200':
          description: "Success"
          schema:
            type: object
            properties:
              record_id:
                type: string
                description: "ZippedScript degree verification record identifier"
              two_factor:
                type: boolean
                description: "If a two-factor authentication code is required"
        "201":
          description: "Request must be of type 'multipart/form-data' or 'application/json' -- or -- Missing parameters -- or -- Not a valid country code -- or -- Not a valid school code"
        "401":
          description: "Bad username or password"
        "503":
          description: "Could not connect to database"
      security:
      - Bearer: []
  /degree_verification/two_factor:
    post:
      tags:
      - "Degree Verification"
      summary: "Submit a 2-fa code for a verification"
      description: "Endpoint allows for the submission of a f-fa code related to a specific record_id"
      operationId: "degreeverificationtwofactor"
      consumes:
      - "application/json"
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "record_id"
        in: "query"
        description: "ZippedScript degree verification record identifier"
        required: true
        type: "string"
      - name: "code"
        in: "query"
        description: "Two factor code associated with the given record_id"
        required: true
        type: "string"
      responses:
        '200':
          description: "Success"
          schema:
            type: object
            properties:
              record_id:
                type: string
                description: "ZippedScript degree verification record identifier"
        "201":
          description: "Request must be of type 'multipart/form-data' or 'application/json' -- or -- Missing parameters -- or -- Not a valid country code -- or -- Not a valid school code"
        "401":
          description: "Bad code entered"
        "503":
          description: "Could not connect to database"
      security:
      - Bearer: []
  /degree_verification/result:
    post:
      tags:
      - "Degree Verification"
      summary: "Request the results of a degree verification"
      description: "Endpoint allows partners to request both the status (e.g., in progress/completed) as well as the results of a degree verification"
      operationId: "degreeverificationresult"
      consumes:
      - "application/json"
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "record_id"
        in: "query"
        description: "The record_id associated with the verification result"
        required: true
        type: "string"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/DegreeVerification"
        "201":
          description: "Request must be of type 'multipart/form-data' or 'application/json' -- or -- Missing parameters"
        "503":
          description: "Could not connect to database"
      security:
      - Bearer: []
  /enrolment_verification/countries:
    get:
      tags:
      - "Enrolment Verification"
      summary: "Return a list of available countries"
      description: "Endpoint returns a list of currently available countries for enrolment verification"
      operationId: "enrolmentverificationgetcountries"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Countries"
  /enrolment_verification/country/{country_code}:
    get:
      tags:
      - "Enrolment Verification"
      summary: "Return a list of available schools for enrolment verification"
      description: "Endpoint returns a list of available schools for enrolment verification according to the country_code provided"
      operationId: "enrolmentverificationgetschools"
      produces:
      - "application/json"
      parameters:
      - name: "country_code"
        in: "path"
        description: "2 Letter Country Code in ISO 3166-1 Format"
        required: true
        type: "string"
      responses:
        "200":
          description: "Success"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Schools"
        "201":
          description: "Country not found"
  /enrolment_verification/new:
    post:
      tags:
      - "Enrolment Verification"
      summary: "Request a new enrolment verification"
      description: "Endpoint allows partners to request a new enrolment verification"
      operationId: "enrolmentverificationnew"
      consumes:
      - "application/json"
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "country"
        in: "query"
        description: "2 letter country code (ISO 3166-1 format)"
        required: true
        type: "string"
      - name: "school"
        in: "query"
        description: "ZippedScript school code/identifier"
        required: true
        type: "string"
      - name: "username"
        in: "query"
        description: "The student username as defined by the school"
        required: true
        type: "string"
      - name: "password"
        in: "query"
        description: "The student password for login in clear text"
        required: true
        type: "string"
      responses:
        '200':
          description: "Success"
          schema:
            type: object
            properties:
              record_id:
                type: string
                description: "ZippedScript degree verification record identifier"
        "201":
          description: "Request must be of type 'multipart/form-data' or 'application/json' -- or -- Missing parameters -- or -- Not a valid country code -- or -- Not a valid school code"
        "401":
          description: "Bad username or password"
        "503":
          description: "Could not connect to database"
      security:
      - Bearer: []
  /enrolment_verification/result:
    post:
      tags:
      - "Enrolment Verification"
      summary: "Request the results of an enrolment verification"
      description: "Endpoint allows partners to request both the status (e.g., in progress/completed) as well as the results of an enrolment verification"
      operationId: "enrolmentverificationresult"
      consumes:
      - "application/json"
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "record_id"
        in: "query"
        description: "The record_id associated with the verification result"
        required: true
        type: "string"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/EnrolmentVerification"
        "201":
          description: "Request must be of type 'multipart/form-data' or 'application/json' -- or -- Missing parameters"
        "503":
          description: "Could not connect to database"
      security:
      - Bearer: []


















  /images/{country_code}/{school_code}:
    get:
      tags:
      - "Images"
      summary: "Return a school's logo"
      description: "Return a logo in .png format corresponding with the country_code and school_code provided"
      operationId: "getschoollogo"
      produces:
      - ".png"
      parameters:
      - name: "country_code"
        in: "path"
        description: "2 Letter Country Code in ISO 3166-1 Format"
        required: true
        type: "string"
      - name: "school_code"
        in: "path"
        description: "ZippedScript School Code/Identifier"
        required: true
        type: "string"
      responses:
        "200":
          description: "Success"
          schema:
            type: file
            format: .png
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      msg:
        type: "string"
      data:
        type: "object"
  Countries:
    type: "object"
    properties:
      Code:
        type: "string"
        description: "2 letter country code (ISO 3166-1 format)"
      Name:
        type: "string"
        description: "Country Name"
  Schools:
    type: "object"
    properties:
      Code:
        type: "string"
        description: "ZippedScript school code/identifier"
      Name:
        type: "string"
        description: "School name"
      System:
        type: "string"
        description: "Name of the school's validation system"
      U:
        type: "string"
        description: "Username descriptor used by the school (e.g., MyUniversityID)"
      P:
        type: "string"
        description: "Password descriptor used by the school (e.g., PIN)"
  DegreeVerification:
    type: "object"
    properties:
      record_id:
        type: "string"
        description: "ZippedScript record_id associated with the verification"
      country:
        type: "string"
        description: "2 letter country code (ISO 3166-1 format)"
      school_id:
        type: "string"
        description: "ZippedScript school code/identifier"
      in_progress:
        type: "boolean"
        description: "true = verification is still in progress, false = verification is complete"
      success:
        type: "boolean"
        description: "true = verification was successful, false = verification was NOT successful, null = no data (e.g., verification in progress)"
      name:
        type: "string"
        description: "Student name as it appears in the school's systems, null = no data (e.g., verification in progress)"
      degree:
        type: "string"
        description: "Degree name/type as it appears in the school's systems, null = no data (e.g., verification in progress)"
      graduated:
        type: "string"
        description: "Date of graduation as it appears in the school's systems, null = no data (e.g., verification in progress)"
      entered_on:
        type: "string"
        description: "Date associated with when a verification was requested"
      verified_on:
        type: "string"
        description: "Date associated with when a verification took place, null = no data (e.g., verification in progress)"
  EnrolmentVerification:
    type: "object"
    properties:
      record_id:
        type: "string"
        description: "ZippedScript record_id associated with the verification"
      country:
        type: "string"
        description: "2 letter country code (ISO 3166-1 format)"
      school_id:
        type: "string"
        description: "ZippedScript school code/identifier"
      in_progress:
        type: "boolean"
        description: "true = verification is still in progress, false = verification is complete"
      success:
        type: "boolean"
        description: "true = verification was successful, false = verification was NOT successful, null = no data (e.g., verification in progress)"
      entered_on:
        type: "string"
        description: "Date associated with when a verification was requested"
      verified_on:
        type: "string"
        description: "Date associated with when a verification took place, null = no data (e.g., verification in progress)"